import type { NextPage } from 'next'
import Head from 'next/head'

import { SocialMedia } from '../components/SocialMedia'
import { User } from '../components/User'

import {getMediasCard} from './api/socialMedia'
import {getUser} from './api/userData'

import styles from '../styles/Card.module.scss'

const Card: NextPage = () => {
  const medias = getMediasCard();
  const user = getUser();

  return (
    <div className={styles.container}>
      <Head>
        <title>Gustavo Henriques</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <div className={styles.summary}>

      <User 
            logo={user.logo} 
            image={user.image} 
            alt_image={user.alt_image} 
            office={user.office}
            name={user.name}
      />
      <section className={styles.socialMedias}>
        { medias.map((media) => {
          return (<SocialMedia
            key={media.title}
            type='C'
            title={media.title}
            icon={media.icon}
            href={media.href}
            target={media.target}
            />)
          })}
      </section>
      </div>
    </div>
  )
}

export default Card
