import type { NextPage } from 'next'
import Head from 'next/head'

import { SocialMedia } from '../components/SocialMedia'
import {getMedias} from './api/socialMedia'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const medias = getMedias();

  return (
    <div className={styles.container}>
      <Head>
        <title>Gustavo Henriques</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {medias.map((media) => {
        return (<SocialMedia
          key={media.title}
          type='W'
          title={media.title}
          icon={media.icon}
          href={media.href}
          />)
        })}

    </div>
  )
}

export default Home
